### ISSUE TITLE
@release-it/conventional-changelog - Option for no change log

### ISSUE THREAD

**Issue by Zamiell** [release-it/conventional-changelog#48]
Hello and thanks for the tool.

I am trying out `release-it`. In my monorepo, I use conventional commits, so I therefore want `release-it` to auto-increment the version based on the commit history. Thus, it seems like I need to use the `@release-it/conventional-changelog` plugin to do this. However, I don't want to generate a changelog. And it seems like this plugin *always* generates a changelog.

Will you accept a PR for a new option that disables the changelog?

**Comment by webpro** [comment]
Yes, that would be a good option to have. There's already `ignoreRecommendedBump`.

**Comment by pedrosodre** [comment]
Is that already possible? Also, can we ignore the changelog for a specific execution with a cli option (like `--no-changelog`)?

**Comment by fsmaia** [comment]
> Is that already possible? Also, can we ignore the changelog for a specific execution with a cli option (like `--no-changelog`)?

This would be amazing!

**Comment by webpro** [comment]
Could somebody using this plugin please try to set `"infile": false`?

I just added a test for and seems to work as intended (40869a157ed33dfb9e31ccd53bc3415fa5e3a7b5).

**Comment by fsmaia** [comment]
It indeed works.

In my use case scenario, I want to skip the changelog for pre-releases. To achieve that, I would have to run a bash script that modifies the config file dynamically within my CI and then ignores this file in git so the working directory would be clean before triggering release-it, which seems to be hacky.

That's why a CLI flag would be handy!

I can help with coding if you will.

**Comment by fsmaia** [comment]
I figured out that the `release-it`'s CLI-to-config behavior covers it:
```sh
npx release-it --plugins.'@release-it/conventional-changelog'.infile=false
```
